# Generated by Django 3.1.3 on 2021-10-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
